[package]
name = "basic_study"
version = "0.0.1"
authors = ["jy00464346 <jy00464346@163.com>"]

[dependencies]
rand = "*"
libc = "*"
rustc-serialize = "*"

[lib]
name="test"
path="src/lib/libtest.rs"
crate_type = ["dylib"]
